### ISSUE TITLE
can you provide the trainning code?

### ISSUE THREAD

**Issue by yuzhijun2** [Klitter/Pyramidal_Person_ReID#1]
can you provide the trainning code?

**Comment by Klitter** [comment]
> can you provide the trainning code?

It is very easy to train the pyramidal model base on other open source code like MGN.

**Comment by bochuanwu** [comment]
> > can you provide the trainning code?
> 
> It is very easy to train the pyramidal model base on other open source code like MGN.

have you used flip image concate with origin image to predict the result in test code？
and have you use cosin distance or Euclidean Distance for test?
really need your help.
