### ISSUE TITLE
how to get the result MAP?

### ISSUE THREAD

**Issue by bochuanwu** [Klitter/Pyramidal_Person_ReID#2]
have you used flip image concate with origin image to predict the result in test code？
and have you use cosin distance or Euclidean Distance for test?
really need your help.

**Comment by Klitter** [comment]
> have you used flip image concate with origin image to predict the result in test code？
> and have you use cosin distance or Euclidean Distance for test?
> really need your help.

I upload some files to do a evaluation demo which may help you.
The evaluation process is quite slow and it may cost several minutes.

**Comment by bochuanwu** [comment]
> > have you used flip image concate with origin image to predict the result in test code？
> > and have you use cosin distance or Euclidean Distance for test?
> > really need your help.
> 
> I upload some files to do a evaluation demo which may help you.
> The evaluation process is quite slow and it may cost several minutes.

thank you
